stages:
    -  stage_build
    -  stage_test
    -  stage_deploy_dev
    -  stage_deploy_prd

variables:
  LOG_FILE: log.txt

default:
  artifacts:
      paths:
          - $LOG_FILE
      
build_job:
    stage: stage_build
    script:
        - echo "---Build_startied--" >> $LOG_FILE
        - docker compose build >> $LOG_FILE 2>&1
        - echo "---Build_completed--" >> $LOG_FILE
    tags:
          - python
    
test_job:
    stage: stage_test
    script:
        - echo "---Test_startied--" >> $LOG_FILE
       
        - echo "---Test_completed--" >> $LOG_FILE
    tags:
          - python
  
deploy_job_dev:
    stage: stage_deploy_dev
    rules:
        - if $CI_COMMIT_BRANCH == "dev"
    script:
        - echo "--Deploy_Startied--" >> $LOG_FILE
        - docker compose up -d >> $LOG_FILE 2>&1
        - echo "--Deploy_Completed--"  >> $LOG_FILE
    tags:
          - python

deploy_job_prd:
    stage: stage_deploy_prd
    rules:
        - if $CI_COMMIT_BRANCH == "main"
    script:
        - echo "--Deploy_Startied--" >> $LOG_FILE
        - docker compose up -d >> $LOG_FILE 2>&1
        - echo "--Deploy_Completed--"  >> $LOG_FILE
    tags:
          - python




